name: Deploy containers to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Configure AWS credentials
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}
    
    - name: Set up SSH key
      uses: actions/checkout@v3
      with:
        private-key: ${{ secrets.UD_SSH_KEY }}

    - name: Adjust SSH key permissions
      run: |
        chmod 400 ${{ secrets.UD_SSH_KEY }}

    - name: Retrieve EC2 hostname
      run: |
        ssh -i ${{ secrets.UD_SSH_KEY }} ec2-user@ec2-3-8-184-137.eu-west-2.compute.amazonaws.com 'hostname'

    # - name: Copy backend files to EC2 instance
    #   run: scp -i ${{ secrets.UD_SSH_KEY }} -r -o StrictHostKeyChecking=no ~/Documents/projects/umrahdeals/server/ ec2-user@3.8.184.137:~/umrahdeals/

    # - name: Copy frontend files to EC2 instance
    #   run: scp -i ${{ secrets.UD_SSH_KEY }} -r -o StrictHostKeyChecking=no ~/Documents/projects/umrahdeals/client/ ec2-user@3.8.184.137:~/umrahdeals/

    # - name: Login to Amazon ECR
    #   id: login-ecr
    #   uses: aws-actions/amazon-ecr-login@v2

    # - name: Build and push Docker images to ECR
    #   run: |
    #     docker build -t 672026569541.dkr.ecr.eu-west-2.amazonaws.com/umrahdeals-backend backend/
    #     docker build -t 672026569541.dkr.ecr.eu-west-2.amazonaws.com/umrahdeals-frontend frontend/
    #     docker push 672026569541.dkr.ecr.eu-west-2.amazonaws.com/umrahdeals-backend
    #     docker push 672026569541.dkr.ecr.eu-west-2.amazonaws.com/umrahdeals-frontend

    # # in terminal type 'echo $UD_SSH_KEY_PATH' to show path of UD ssh key 
    # - name: SSH into EC2 and deploy
    #   run: |
    #     ssh -i ${{ env.UD_SSH_KEY_PATH }}/umrahdeals-kp.pem ec2-user@3.8.184.137 << EOF
    #       # Backend deployment commands
    #       cd /path/to/backend
    #       docker-compose down
    #       docker-compose pull
    #       docker-compose up -d

    #       # Frontend deployment commands
    #       cd /path/to/frontend
    #       docker-compose down
    #       docker-compose pull
    #       docker-compose up -d
    #     EOF
